version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
  # nestjs:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   image: mannasuman134/lebong-orc
  #   environment:
  #     - REDIS_HOST=${REDIS_HOST}
  #     - REDIS_PORT=${REDIS_PORT}
  #   ports:
  #     - '3000:3000' # expose-to-the-world : only-in-the-docker
  #   container_name: lebong-dev-orc
  #   depends_on:
  #     - redis
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
